version: "2"
services:
  account-service-api:
    hostname: account-service-api
    image: account-service-api:0.0.1-SNAPSHOT
    privileged: true
    environment:
     - PORT=8080
     - MONGO_HOST=mongo
     - MONGO_PORT=27017
     - MONGO_DB=demo
     - JAVA_OPTS=-server -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -Xms512m -Xmx512m
    ports:
     - 8080:8080
    links:
     - mongo
  account-ui:
    hostname: account-ui
    image: account-ui:0.0.1-SNAPSHOT
    privileged: true
    environment:
     - PORT=8080
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - ACCOUNT_SERVICE_URL=http://account-service-api:8080
     - JAVA_OPTS=-server -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -Xms512m -Xmx512m
    ports:
     - 8081:8080
    links:
     - account-service-api
     - redis
  mongo:
    hostname: mongo
    image: mongo:latest
    privileged: true
    ports:
     - 27017:27017
  redis:
    hostname: redis
    image: redis:latest
    privileged: true
    ports:
     - 6379:6379
